@echo off
rem call "C:\Program Files\QGIS 3.40.1\bin\o4w_env.bat"

call "C:\Program Files\QGIS 3.22.16\bin\o4w_env.bat"
@echo on
REM set pgacc= --config GML_SKIP_CORRUPTED_FEATURES=TRUE -f "PostgreSQL" PG:"host=localhost user=postgres dbname=ballerup_oktober2 password=ukulemy active_schema=sweco2 port=5433" -lco EXTRACT_SCHEMA_FROM_LAYER_NAME=FALSE 
REM set pgacc= -f "GPKG" d:\temp\data123456.gpkg 
REM set pgacc= -makevalid  --config GML_SKIP_CORRUPTED_FEATURES=TRUE -update -f "GPKG" data.gpkg 

REM set pgacc= -s_srs EPSG:4326 -t_srs EPSG:25832 --config OGR_PG_ENABLE_METADATA=FALSE  -s_srs EPSG:4326 -t_srs EPSG:25832  -f "PostgreSQL" PG:"host=common-db.gc2.io user=ballerup_park dbname=ballerup_park password=gaker9jI active_schema=sweco2 port=5432" -lco EXTRACT_SCHEMA_FROM_LAYER_NAME=FALSE 
REM set pgacc= -skipfailures --config GML_SKIP_CORRUPTED_FEATURES=TRUE -s_srs EPSG:4326 -t_srs EPSG:25832  -f "PostgreSQL" PG:"host=common-db.gc2.io user=ballerup_park dbname=ballerup_park password=gaker9jI active_schema=sweco5 port=5432" -lco EXTRACT_SCHEMA_FROM_LAYER_NAME=FALSE 
set pgacc= -skipfailures -lco DIM=2 -lco GEOMETRY_NAME=geom -s_srs EPSG:4326 -t_srs EPSG:25832  -f "PostgreSQL" PG:"host=common-db.gc2.io user=ballerup_park dbname=ballerup_park password=gaker9jI active_schema=driftweb port=5432" -lco EXTRACT_SCHEMA_FROM_LAYER_NAME=FALSE 
REM set pgacc= -s_srs EPSG:4326 -t_srs EPSG:25832  -f "PostgreSQL" PG:"host=localhost dbname=ballerup_park user=postgres password=ukulemy active_schema=sweco2 port=5432" -lco EXTRACT_SCHEMA_FROM_LAYER_NAME=FALSE 

REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workareas"                             -nln "workareas"                      -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "vvk1.2"                                -nln "vvk1_2"                         -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "vvk1.2m"                               -nln "vvk1_2m"                        -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "vvk1.4"                                -nln "vvk1_4"                         -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "vvk1.4m"                               -nln "vvk1_4m"                        -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "a"                                     -nln "a"                                                    -nlt POINT 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "ana1"                                  -nln "ana1"                           -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "ap"                                    -nln "ap"                             -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "ag"                                    -nln "ag"                             -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "asf"                                   -nln "asf"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "hd24"                                  -nln "hd24"                           -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "av"                                    -nln "av"                             -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_bi"                           -nln "workarea_bi"                    -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_bv"                           -nln "workarea_bv"                    -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "bt"                                    -nln "bt"                             -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "bebs"                                  -nln "bebs"                           -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "befl"                                  -nln "befl"                           -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "bks"                                   -nln "bks"                            -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "bepl"                                  -nln "bepl"                                                 -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "bistr"                                 -nln "bistr"                          -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "bist"                                  -nln "bist"                           -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "be"                                    -nln "be"                             -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "b"                                     -nln "b"                                                    -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_bb"                           -nln "workarea_bb"                    -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "bm"                                    -nln "bm"                                                   -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "bd"                                    -nln "bd"                                                   -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "bbs"                                   -nln "bbs"                                                  -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "borks"                                 -nln "borks"                          -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "bs"                                    -nln "bs"                             -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "brl"                                   -nln "brl"                            -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "bp"                                    -nln "bp"                             -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "bdl"                                   -nln "bdl"                                                  -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "bud"                                   -nln "bud"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "bb"                                    -nln "bb"                             -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "bu"                                    -nln "bu"                             -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "bls"                                   -nln "bls"                                                  -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "bus"                                   -nln "bus"                                                  -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "bygn"                                  -nln "bygn"                           -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_bls"                          -nln "workarea_bls"                   -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "br"                                    -nln "br"                             -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "blp"                                   -nln "blp"                                                  -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "bk"                                    -nln "bk"                                                   -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "cs"                                    -nln "cs"                             -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "csr"                                   -nln "csr"                            -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "cysr"                                  -nln "cysr"                           -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "cyse"                                  -nln "cyse"                                                 -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "cyst"                                  -nln "cyst"                           -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "cykelsti_vinterklasse_i_028"           -nln "cykelsti_vinterklasse_i_028"    -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_di"                           -nln "workarea_di"                    -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "dk"                                    -nln "dk"                                                   -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "eut"                                   -nln "eut"                                                  -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "ful"                                   -nln "ful"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_ful"                          -nln "workarea_ful"                   -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_fr"                           -nln "workarea_fr"                    -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_fm"                           -nln "workarea_fm"                    -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_fejcs"                        -nln "workarea_fejcs"                 -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_fejf"                         -nln "workarea_fejf"                  -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_fejv1"                        -nln "workarea_fejv1"                 -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_fejv2"                        -nln "workarea_fejv2"                 -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "fst"                                   -nln "fst"                                                  -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "flb"                                   -nln "flb"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "fh"                                    -nln "fh"                             -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "fo"                                    -nln "fo"                             -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "fok"                                   -nln "fok"                                                  -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "foh"                                   -nln "foh"                            -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_fs"                           -nln "workarea_fs"                    -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "fabos"                                 -nln "fabos"                          -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "fafag"                                 -nln "fafag"                          -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "fafagos"                               -nln "fafagos"                        -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "fagobos"                               -nln "fagobos"                        -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "fagos"                                 -nln "fagos"                          -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "fdf"                                   -nln "fdf"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "fdl"                                   -nln "fdl"                            -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "vfdldobbelt"                           -nln "vfdldobbelt"                    -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "fbmv"                                  -nln "fbmv"                           -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "fm"                                    -nln "fm"                             -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "fb"                                    -nln "fb"                                                   -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "fvh"                                   -nln "fvh"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "fut"                                   -nln "fut"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "fg"                                    -nln "fg"                             -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "fgg"                                   -nln "fgg"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "fgv"                                   -nln "fgv"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "fgvno"                                 -nln "fgvno"                          -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "fg1"                                   -nln "fg1"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "fg1no"                                 -nln "fg1no"                          -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "fg2"                                   -nln "fg2"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "fg2no"                                 -nln "fg2no"                          -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "ftav"                                  -nln "ftav"                                                 -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "fri"                                   -nln "fri"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "gb"                                    -nln "gb"                             -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "grf"                                   -nln "grf"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "gks"                                   -nln "gks"                            -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "g"                                     -nln "g"                              -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "gra"                                   -nln "gra"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_gv"                           -nln "workarea_gv"                    -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "groeft_054"                            -nln "groeft_054"                     -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "gasf"                                  -nln "gasf"                           -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "gfl"                                   -nln "gfl"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "havelod_057"                           -nln "havelod_057"                    -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "he"                                    -nln "he"                             -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "ha"                                    -nln "ha"                             -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "kh"                                    -nln "kh"                             -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "hb"                                    -nln "hb"                             -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_is"                           -nln "workarea_is"                    -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "iv"                                    -nln "iv"                             -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "ib"                                    -nln "ib"                             -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "if"                                    -nln "if"                             -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "inst"                                  -nln "inst"                           -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "instpl"                                -nln "instpl"                         -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "inve"                                  -nln "inve"                           -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "j"                                     -nln "j"                              -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "ks"                                    -nln "ks"                             -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "kpl"                                   -nln "kpl"                                                  -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "kp"                                    -nln "kp"                                                   -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "kli"                                   -nln "kli"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "kps"                                   -nln "kps"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_kbb"                          -nln "workarea_kbb"                   -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_kbbv"                         -nln "workarea_kbbv"                  -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_kbc"                          -nln "workarea_kbc"                   -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_kbi"                          -nln "workarea_kbi"                   -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_kbn"                          -nln "workarea_kbn"                   -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_kbr"                          -nln "workarea_kbr"                   -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_kbs"                          -nln "workarea_kbs"                   -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_keb"                          -nln "workarea_keb"                   -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_klp"                          -nln "workarea_klp"                   -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_kms"                          -nln "workarea_kms"                   -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_km"                           -nln "workarea_km"                    -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_kmb"                          -nln "workarea_kmb"                   -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_ks"                           -nln "workarea_ks"                    -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_ksb"                          -nln "workarea_ksb"                   -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_kss"                          -nln "workarea_kss"                   -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "kg"                                    -nln "kg"                             -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "k"                                     -nln "k"                                                    -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "kl"                                    -nln "kl"                                                   -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "ll"                                    -nln "ll"                             -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "lmu"                                   -nln "lmu"                                                  -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "lr"                                    -nln "lr"                                                   -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "lrf"                                   -nln "lrf"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_lr"                           -nln "workarea_lr"                    -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "lhk"                                   -nln "lhk"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "lia"                                   -nln "lia"                            -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "l"                                     -nln "l"                                                    -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "lak"                                   -nln "lak"                                                  -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "lb"                                    -nln "lb"                             -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "ls"                                    -nln "ls"                             -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "lv"                                    -nln "lv"                             -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "lful"                                  -nln "lful"                           -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_lfu"                          -nln "workarea_lfu"                   -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "mk"                                    -nln "mk"                             -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "markvej_077"                           -nln "markvej_077"                    -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "me"                                    -nln "me"                             -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_mh"                           -nln "workarea_mh"                    -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "mose_078"                              -nln "mose_078"                       -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "mu"                                    -nln "mu"                                                   -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "m"                                     -nln "m"                              -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "ml"                                    -nln "ml"                                                   -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "ng"                                    -nln "ng"                             -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_nh"                           -nln "workarea_nh"                    -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_nohd1"                        -nln "workarea_nohd1"                 -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_no"                           -nln "workarea_no"                    -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_ngr"                          -nln "workarea_ngr"                   -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_nog"                          -nln "workarea_nog"                   -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_nohd"                         -nln "workarea_nohd"                  -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_nogr"                         -nln "workarea_nogr"                  -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "ns"                                    -nln "ns"                             -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "nac"                                   -nln "nac"                                                  -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "nr"                                    -nln "nr"                                                   -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "asfob"                                 -nln "asfob"                          -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "fsa"                                   -nln "fsa"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_pk"                           -nln "workarea_pk"                    -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "vvk3p"                                 -nln "vvk3p"                          -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "pkp"                                   -nln "pkp"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "pga"                                   -nln "pga"                                                  -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "ps"                                    -nln "ps"                             -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "pst"                                   -nln "pst"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "plankevaerk_089"                       -nln "plankevaerk_089"                -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "pk"                                    -nln "pk"                                                   -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_pc"                           -nln "workarea_pc"                    -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_pcx"                          -nln "workarea_pcx"                   -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "pvl"                                   -nln "pvl"                                                  -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "p"                                     -nln "p"                                                    -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "pb"                                    -nln "pb"                                                   -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "pa"                                    -nln "pa"                                                   -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "klp"                                   -nln "klp"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "pn"                                    -nln "pn"                                                   -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "ggrg"                                  -nln "ggrg"                           -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "rg"                                    -nln "rg"                             -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "rg1"                                   -nln "rg1"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "rg2"                                   -nln "rg2"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "rgb"                                   -nln "rgb"                            -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "rg3"                                   -nln "rg3"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "rg5"                                   -nln "rg5"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "rskr"                                  -nln "rskr"                           -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "rgt"                                   -nln "rgt"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "rpf"                                   -nln "rpf"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "rpl"                                   -nln "rpl"                            -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "rb"                                    -nln "rb"                                                   -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_rv"                           -nln "workarea_rv"                    -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_rvms"                         -nln "workarea_rvms"                  -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "rob"                                   -nln "rob"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "rbe"                                   -nln "rbe"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_rw"                           -nln "workarea_rw"                    -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "rv"                                    -nln "rv"                             -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "roersump_098"                          -nln "roersump_098"                   -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "sfs"                                   -nln "sfs"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "sobo"                                  -nln "sobo"                                                 -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "sasi"                                  -nln "sasi"                                                 -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_smhd"                         -nln "workarea_smhd"                  -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "sand"                                  -nln "sand"                           -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "sf"                                    -nln "sf"                                                   -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "sak"                                   -nln "sak"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "shb"                                   -nln "shb"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "sfb"                                   -nln "sfb"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "she"                                   -nln "she"                                                  -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "sa"                                    -nln "sa"                                                   -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_sk"                           -nln "workarea_sk"                    -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "sk"                                    -nln "sk"                             -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_sc"                           -nln "workarea_sc"                    -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "skur"                                  -nln "skur"                           -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "sps"                                   -nln "sps"                                                  -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "ss"                                    -nln "ss"                             -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "snf"                                   -nln "snf"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "sns"                                   -nln "sns"                            -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "sr"                                    -nln "sr"                             -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "svb"                                   -nln "svb"                                                  -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "sm"                                    -nln "sm"                                                   -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "sp"                                    -nln "sp"                             -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "spl"                                   -nln "spl"                                                  -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "sv"                                    -nln "sv"                                                   -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "st"                                    -nln "st"                             -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "s"                                     -nln "s"                                                    -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "sd"                                    -nln "sd"                             -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "stm"                                   -nln "stm"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "sh"                                    -nln "sh"                                                   -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "stk"                                   -nln "stk"                            -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "stsk"                                  -nln "stsk"                           -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_sum"                          -nln "workarea_sum"                   -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_sum1"                         -nln "workarea_sum1"                  -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_sumo"                         -nln "workarea_sumo"                  -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "sveller_119"                           -nln "sveller_119"                    -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "soe"                                   -nln "soe"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_tu"                           -nln "workarea_tu"                    -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_tuvs"                         -nln "workarea_tuvs"                  -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "terraenbygvaerker_121"                 -nln "terraenbygvaerker_121"          -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "trm"                                   -nln "trm"                            -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "terraenudstyr_122"                     -nln "terraenudstyr_122"              -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "terraenudstyr_l_123"                   -nln "terraenudstyr_l_123"            -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "tu"                                    -nln "tu"                                                   -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_to"                           -nln "workarea_to"                    -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_to2"                          -nln "workarea_to2"                   -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_tp"                           -nln "workarea_tp"                    -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "ts"                                    -nln "ts"                             -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "trpb"                                  -nln "trpb"                                                 -nlt POINT        
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "trpf"                                  -nln "trpf"                           -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "trpl"                                  -nln "trpl"                           -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING
REM ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "th"                                    -nln "th"                             -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING
ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "tr"                                    -nln "tr"                                                   -nlt POINT        
ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "tb"                                    -nln "tb"                             -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "trr"                                   -nln "trr"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "tst"                                   -nln "tst"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "trte"                                  -nln "trte"                           -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_ub"                           -nln "workarea_ub"                    -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_ufk"                          -nln "workarea_ufk"                   -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_uhv"                          -nln "workarea_uhv"                   -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_ubf"                          -nln "workarea_ubf"                   -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "vandloeb_137"                          -nln "vandloeb_137"                   -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING
ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "vr"                                    -nln "vr"                             -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING
ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "v2s"                                   -nln "v2s"                            -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING
ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "v2smr"                                 -nln "v2smr"                          -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING
ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "v4s"                                   -nln "v4s"                            -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING
ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "v4smr"                                 -nln "v4smr"                          -nlt PROMOTE_TO_MULTI -nlt MULTILINESTRING
ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "vbf"                                   -nln "vbf"                                                  -nlt POINT        
ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "vns"                                   -nln "vns"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_evr"                          -nln "workarea_evr"                   -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "vs"                                    -nln "vs"                                                   -nlt POINT        
ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_vdih"                         -nln "workarea_vdih"                  -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_veuh"                         -nln "workarea_veuh"                  -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_vsoih"                        -nln "workarea_vsoih"                 -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_vsoi"                         -nln "workarea_vsoi"                  -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_vvh"                          -nln "workarea_vvh"                   -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_vt"                           -nln "workarea_vt"                    -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "vvk2f"                                 -nln "vvk2f"                          -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "vtg"                                   -nln "vtg"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "lt"                                    -nln "lt"                                                   -nlt POINT        
ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "os"                                    -nln "os"                                                   -nlt POINT        
ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "aest"                                  -nln "aest"                           -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "olb"                                   -nln "olb"                            -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 
ogr2ogr %pgacc% WFS:"https://wfs-ext.gmpark.dk/geoserver/ws_22e14f95-7397-4d9a-b347-b0f4e56dd45c/ows" "workarea_oi"                           -nln "workarea_oi"                    -nlt PROMOTE_TO_MULTI -nlt MULTIPOLYGON 

pause
